-- Создание таблицы фильмов
CREATE TABLE Movies (
                        ID VARCHAR(50) PRIMARY KEY,
                        Title VARCHAR(255) NOT NULL,
                        Year INTEGER NOT NULL,
                        FilePath VARCHAR(500) NOT NULL,
                        CoverPath VARCHAR(500),
                        CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Создание таблицы жанров
CREATE TABLE Genres (
                        ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        Name VARCHAR(100) UNIQUE NOT NULL
);

-- Связь фильмов и жанров (многие-ко-многим)
CREATE TABLE MovieGenres (
                             MovieID VARCHAR(50) REFERENCES Movies(ID) ON DELETE CASCADE,
                             GenreID INTEGER REFERENCES Genres(ID) ON DELETE CASCADE,
                             PRIMARY KEY (MovieID, GenreID)
);

-- Создание таблицы актёров
CREATE TABLE Actors (
                        ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        Name VARCHAR(255) UNIQUE NOT NULL
);

-- Связь фильмов и актёров с ролями
CREATE TABLE MovieActors (
                             MovieID VARCHAR(50) REFERENCES Movies(ID) ON DELETE CASCADE,
                             ActorID INTEGER REFERENCES Actors(ID) ON DELETE CASCADE,
                             CharacterName VARCHAR(255),
                             PRIMARY KEY (MovieID, ActorID)
);

-- Индексы для ускорения поиска
CREATE INDEX IDX_Movies_Year ON Movies(Year);
CREATE INDEX IDX_Movies_Title ON Movies(Title);
CREATE INDEX IDX_Genres_Name ON Genres(Name);
CREATE INDEX IDX_Actors_Name ON Actors(Name);

-- Вставка основных жанров
INSERT INTO Genres (Name) VALUES
                              ('Боевик'), ('Драма'), ('Комедия'), ('Фантастика'), ('Фэнтези'),
                              ('Ужасы'), ('Триллер'), ('Криминал'), ('Мелодрама'), ('Приключения');
