# -------------------------------------------------
# ????? ???????? ??????????
# -------------------------------------------------
app.db-type=firebird 

# -------------------------------------------------
# Spring DataSource (???????????? ? Flyway, ? JPA)
# -------------------------------------------------
spring.datasource.url=jdbc:firebirdsql://localhost:3050//db/cinema.fdb?charset=UTF8&lc_ctype=UTF8
spring.datasource.driver-class-name=org.firebirdsql.jdbc.FBDriver
spring.datasource.username=sysdba
spring.datasource.password=masterkey

# -------------------------------------------------
# Flyway (???????? ??????)
# -------------------------------------------------
flyway.url=jdbc:firebirdsql://localhost:3050//db/cinema.fdb?charset=UTF8&lc_ctype=UTF8
flyway.user=sysdba
flyway.password=masterkey
flyway.driver-class-name=org.firebirdsql.jdbc.FBDriver
# (?? ????????? flyway.enabled=true, ??? ??? ?????? ?????? ?? ?????)

# -------------------------------------------------
# JPA / Hibernate
# -------------------------------------------------
jpa.hibernate.ddl-auto=update
jpa.hibernate.database-platform=org.hibernate.dialect.FirebirdDialect

# -------------------------------------------------
# (???????????) ????????/????????? devtools, ???? ? ?.?.
# -------------------------------------------------
# spring.devtools.add-properties=false   # ???? ?????? ????????? devtools?????????????
# logging.level.web=DEBUG            # ????? ????????? ??? ????????
