SET SQL DIALECT 3;
SET NAMES UTF8;

-- 1. Таблица фильмов
CREATE TABLE Movies (
    ID VARCHAR(50) PRIMARY KEY,
    Title VARCHAR(255),
    Description BLOB,
    FilePath VARCHAR(500) NOT NULL,
    CoverPath VARCHAR(500),
    ReleaseYear INTEGER,
    Status VARCHAR(20) CHECK (Status IN ('released', 'upcoming')),
    Duration INTEGER,
    IsWatched BOOLEAN DEFAULT FALSE,
    DirectorID INTEGER
);

-- 2. Таблица жанров
CREATE TABLE Genres (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(100) UNIQUE NOT NULL
);

-- 3. Связь фильмов и жанров
CREATE TABLE MovieGenres (
    MovieID VARCHAR(50) REFERENCES Movies(ID) ON DELETE CASCADE,
    GenreID INTEGER REFERENCES Genres(ID) ON DELETE CASCADE,
    PRIMARY KEY (MovieID, GenreID)
);

-- 4. Таблица актёров
CREATE TABLE Actors (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(250),
    last_name VARCHAR(250),
    bio VARCHAR(255) NOT NULL
);

-- 5. Связь фильмов и актёров
CREATE TABLE MovieActors (
    MovieID VARCHAR(50) REFERENCES Movies(ID) ON DELETE CASCADE,
    ActorID INTEGER REFERENCES Actors(ID) ON DELETE CASCADE,
    CharacterName VARCHAR(255),
    PRIMARY KEY (MovieID, ActorID)
);

-- 6. Таблица режиссёров
CREATE TABLE Directors (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(255) UNIQUE NOT NULL
);

-- 7. Таблица сериалов
CREATE TABLE Series (
    ID VARCHAR(50) PRIMARY KEY,
    Title VARCHAR(255),
    Description BLOB,
    FilePath VARCHAR(500) NOT NULL,
    CoverPath VARCHAR(500),
    Status VARCHAR(20) CHECK (Status IN ('released', 'ongoing')),
    SeasonsCount INTEGER DEFAULT 0,
    EpisodesCount INTEGER DEFAULT 0,
    IsWatched BOOLEAN DEFAULT FALSE
);

-- 8. Таблица сезонов
CREATE TABLE Seasons (
    ID VARCHAR(50) PRIMARY KEY,
    SeriesID VARCHAR(50) REFERENCES Series(ID) ON DELETE CASCADE,
    SeasonNumber INTEGER NOT NULL,
    EpisodesCount INTEGER DEFAULT 0,
    Status VARCHAR(20) CHECK (Status IN ('released', 'ongoing')),
    FilePath VARCHAR(500),
    Duration INTEGER,
    ReleaseYear INTEGER,
    Title VARCHAR(255),
    IsWatched BOOLEAN DEFAULT FALSE,
    DirectorID INTEGER REFERENCES Directors(ID)
);

-- 9. Таблица серий
CREATE TABLE Episodes (
    ID VARCHAR(50) PRIMARY KEY,
    SeasonID VARCHAR(50) REFERENCES Seasons(ID) ON DELETE CASCADE,
    Title VARCHAR(255),
    Duration INTEGER,
    FilePath VARCHAR(500),
    IsWatched BOOLEAN DEFAULT FALSE,
    EpisodeNumber INTEGER NOT NULL
);

-- 10. Таблица ролей пользователей
CREATE TABLE Users(
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username VARCHAR(100) UNIQUE NOT NULL,
    RoleName VARCHAR(50) NOT NULL CHECK (RoleName IN ('ADMIN', 'moderator', 'user')),
    PasswordHash VARCHAR(255) NOT NULL,
    Email VARCHAR(255)
);

-- 11. Таблица истории просмотров пользователей (для фильмов)
CREATE TABLE UserMovieHistory (
    UserID INTEGER REFERENCES Users(ID) ON DELETE CASCADE,
    MovieID VARCHAR(50) REFERENCES Movies(ID) ON DELETE CASCADE,
    WatchDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Rating INTEGER CHECK (Rating BETWEEN 1 AND 10),
    PRIMARY KEY (UserID, MovieID)
);

-- 12. Таблица истории просмотров пользователей (для сериалов)
CREATE TABLE UserSeriesHistory (
    UserID INTEGER REFERENCES Users(ID) ON DELETE CASCADE,
    SeriesID VARCHAR(50) REFERENCES Series(ID) ON DELETE CASCADE,
    WatchDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Rating INTEGER CHECK (Rating BETWEEN 1 AND 10),
    PRIMARY KEY (UserID, SeriesID)
);

-- 13. Таблица истории просмотров пользователей (для эпизодов)
CREATE TABLE UserEpisodeHistory (
    UserID INTEGER REFERENCES Users(ID) ON DELETE CASCADE,
    EpisodeID VARCHAR(50) REFERENCES Episodes(ID) ON DELETE CASCADE,
    WatchDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Rating INTEGER CHECK (Rating BETWEEN 1 AND 10),
    PRIMARY KEY (UserID, EpisodeID)
);

-- 14. Таблица избранного пользователей (фильмы)
CREATE TABLE UserFavorites (
    UserID INTEGER REFERENCES Users(ID) ON DELETE CASCADE,
    MovieID VARCHAR(50) REFERENCES Movies(ID) ON DELETE CASCADE,
    AddedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (UserID, MovieID)
);

-- 15. Таблица избранного пользователей (сериалы)
CREATE TABLE UserFavoriteSeries (
    UserID INTEGER REFERENCES Users(ID) ON DELETE CASCADE,
    SeriesID VARCHAR(50) REFERENCES Series(ID) ON DELETE CASCADE,
    AddedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (UserID, SeriesID)
);

-- Добавляем внешние ключи после создания всех таблиц
ALTER TABLE Movies ADD CONSTRAINT FK_Movies_DirectorID FOREIGN KEY (DirectorID) REFERENCES Directors(ID);
ALTER TABLE Seasons ADD CONSTRAINT FK_Seasons_DirectorID FOREIGN KEY (DirectorID) REFERENCES Directors(ID);

-- 100. Индексы
CREATE INDEX IDX_Movies_ReleaseYear ON Movies(ReleaseYear);
CREATE INDEX IDX_Movies_Title ON Movies(Title);
CREATE INDEX IDX_Actors_Name ON Actors(Name);
CREATE INDEX IDX_MovieGenres_MovieID ON MovieGenres(MovieID);
CREATE INDEX IDX_MovieGenres_GenreID ON MovieGenres(GenreID);
CREATE INDEX IDX_MovieActors_MovieID ON MovieActors(MovieID);
CREATE INDEX IDX_MovieActors_ActorID ON MovieActors(ActorID);
CREATE INDEX IDX_Movies_DirectorID ON Movies(DirectorID);
CREATE INDEX IDX_Movies_IsWatched ON Movies(IsWatched);
CREATE INDEX IDX_Movies_Status ON Movies(Status);
CREATE INDEX IDX_Series_Title ON Series(Title);
CREATE INDEX IDX_Series_IsWatched ON Series(IsWatched);
CREATE INDEX IDX_Series_Status ON Series(Status);
CREATE INDEX IDX_Seasons_SeriesID ON Seasons(SeriesID);
CREATE INDEX IDX_Seasons_SeasonNumber ON Seasons(SeriesID, SeasonNumber);
CREATE INDEX IDX_Seasons_IsWatched ON Seasons(IsWatched);
CREATE INDEX IDX_Seasons_DirectorID ON Seasons(DirectorID);
CREATE INDEX IDX_Episodes_SeasonID ON Episodes(SeasonID);
CREATE INDEX IDX_Episodes_EpisodeNumber ON Episodes(SeasonID, EpisodeNumber);
CREATE INDEX IDX_Episodes_IsWatched ON Episodes(IsWatched);
CREATE INDEX IDX_Directors_Name ON Directors(Name);
CREATE INDEX IDX_Movies_ReleaseYear_Title ON Movies(ReleaseYear, Title);
CREATE INDEX IDX_Series_Status_Title ON Series(Status, Title);

-- Индексы для новых таблиц
CREATE INDEX IDX_Users_Username ON Users(Username);
CREATE INDEX IDX_Users_Email ON Users(Email);
CREATE INDEX IDX_Users_RoleName ON Users(RoleName);
CREATE INDEX IDX_UserMovieHistory_UserID ON UserMovieHistory(UserID);
CREATE INDEX IDX_UserMovieHistory_MovieID ON UserMovieHistory(MovieID);
CREATE INDEX IDX_UserSeriesHistory_UserID ON UserSeriesHistory(UserID);
CREATE INDEX IDX_UserSeriesHistory_SeriesID ON UserSeriesHistory(SeriesID);
CREATE INDEX IDX_UserEpisodeHistory_UserID ON UserEpisodeHistory(UserID);
CREATE INDEX IDX_UserEpisodeHistory_EpisodeID ON UserEpisodeHistory(EpisodeID);
CREATE INDEX IDX_UserFavorites_UserID ON UserFavorites(UserID);
CREATE INDEX IDX_UserFavorites_MovieID ON UserFavorites(MovieID);
CREATE INDEX IDX_UserFavoriteSeries_UserID ON UserFavoriteSeries(UserID);
CREATE INDEX IDX_UserFavoriteSeries_SeriesID ON UserFavoriteSeries(SeriesID);